name: Docker release image

on:
  workflow_call:
    inputs:
      GLOBAL_REPO_NAME:
        required: true
        type: string
      PATH_TO_DOCKERFILE:
        required: true
        type: string
      GLOBAL_IMAGE_NAME:
        required: true
        type: string
      GLOBAL_FRAMEWORK:
        required: true
        type: string
    secrets:
      VAULT_ADDR:
        required: true
      CI_SECRET_READER_PERIODIC_TOKEN:
        required: true
      VAULTCA:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  build-context:
    runs-on: ubuntu-latest
    steps:
      - uses: danubetech/github-action-log-build-context@v0.1.0

  build-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write

    steps:
      - name: Import Secrets maven
        if: ${{ inputs.GLOBAL_FRAMEWORK == 'maven' || inputs.GLOBAL_FRAMEWORK == 'triggered' || inputs.GLOBAL_FRAMEWORK == 'did-science' }}
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
          caCertificate: ${{ secrets.VAULTCA }}
          secrets: |
            ci/data/gh-workflows/${{ inputs.GLOBAL_REPO_NAME }} username | DOCKER_USERNAME ;
            ci/data/gh-workflows/${{ inputs.GLOBAL_REPO_NAME }} password | DOCKER_PASSWORD ;
            ci/data/gh-workflows/maven-danubetech-nexus username | MAVEN_USERNAME ;
            ci/data/gh-workflows/maven-danubetech-nexus password | MAVEN_PASSWORD

      - name: Import Secrets generic
        if: ${{ inputs.GLOBAL_FRAMEWORK != 'maven' && inputs.GLOBAL_FRAMEWORK != 'triggered' }}
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
          caCertificate: ${{ secrets.VAULTCA }}
          secrets: |
            ci/data/gh-workflows/${{ inputs.GLOBAL_REPO_NAME }} username | DOCKER_USERNAME ;
            ci/data/gh-workflows/${{ inputs.GLOBAL_REPO_NAME }} password | DOCKER_PASSWORD

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js environment
        if: ${{ inputs.GLOBAL_FRAMEWORK == 'node' }}
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Setup Java
        if: ${{ inputs.GLOBAL_FRAMEWORK == 'maven' || inputs.GLOBAL_FRAMEWORK == 'triggered' }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure Maven Settings
        if: ${{ inputs.GLOBAL_FRAMEWORK == 'maven' || inputs.GLOBAL_FRAMEWORK == 'triggered' ||  inputs.GLOBAL_FRAMEWORK == 'did-science' }}
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << 'EOF'
          <settings>
            <servers>
              <server>
                <id>danubetech-maven-snapshots</id>
                <username>${{ env.MAVEN_USERNAME }}</username>
                <password>${{ env.MAVEN_PASSWORD }}</password>
              </server>
              <server>
                <id>danubetech-maven-releases</id>
                <username>${{ env.MAVEN_USERNAME }}</username>
                <password>${{ env.MAVEN_PASSWORD }}</password>
              </server>
              <server>
                <id>danubetech-maven-internal</id>
                <username>${{ env.MAVEN_USERNAME }}</username>
                <password>${{ env.MAVEN_PASSWORD }}</password>
              </server>
              <server>
                <id>danubetech-maven-internal-releases</id>
                <username>${{ env.MAVEN_USERNAME }}</username>
                <password>${{ env.MAVEN_PASSWORD }}</password>
              </server>
              <server>
                <id>danubetech-maven-internal-snapshots</id>
                <username>${{ env.MAVEN_USERNAME }}</username>
                <password>${{ env.MAVEN_PASSWORD }}</password>
              </server>
              <server>
                <id>danubetech-maven-internal-releases</id>
                <username>${{ env.MAVEN_USERNAME }}</username>
                <password>${{ env.MAVEN_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Validate pom.xml
        if: ${{ inputs.GLOBAL_FRAMEWORK == 'maven' && inputs.GLOBAL_FRAMEWORK != 'triggered' }}
        run: |
          echo "$SETTINGS_FILE" > ./multi-server-template.xml
          envsubst < ./multi-server-template.xml > ./settings.xml
          mvn validate -P ci --settings ./settings.xml

      - name: Get Version for Triggered Build
        if: ${{ inputs.GLOBAL_FRAMEWORK == 'triggered' }}
        id: get-version-triggered
        run: |
          # Get the latest version tag from git
          RELEASE_VERSION=$(git tag --sort=-creatordate | head -n 1)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Increment Maven Version
        if: ${{ inputs.GLOBAL_FRAMEWORK == 'maven' && inputs.GLOBAL_FRAMEWORK != 'triggered'}}
        id: increment-version-maven
        run: |
          # Get current version without -SNAPSHOT
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
          
          # Split version into major and minor (we know it's in format X.Y)
          IFS='.' read -r major minor <<< "$CURRENT_VERSION"
          
          # For patch releases, we need to use the last released version
          if [[ "${{ github.event.inputs.release_type }}" == "patch" ]]; then
            # Get the last version tag
            LAST_VERSION=$(git tag -l | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
            if [[ -n "$LAST_VERSION" ]]; then
              IFS='.' read -r major minor patch <<< "$LAST_VERSION"
              RELEASE_VERSION="${major}.${minor}.$((patch + 1))"
            else
              RELEASE_VERSION="${major}.${minor}.1"
            fi
            NEXT_VERSION="${major}.${minor}-SNAPSHOT"
          else
            case "${{ github.event.inputs.release_type }}" in
              major)
                major=$((major + 1))
                RELEASE_VERSION="${major}.0.0"
                NEXT_VERSION="${major}.0-SNAPSHOT"
                ;;
              minor)
                RELEASE_VERSION="${major}.${minor}.0"
                minor=$((minor + 1))
                NEXT_VERSION="${major}.${minor}-SNAPSHOT"
                ;;
              *)
                echo "Invalid release type: ${{ github.event.inputs.release_type }}"
                exit 1
                ;;
            esac
          fi
          
          # Set release version
          mvn versions:set -DnewVersion=$RELEASE_VERSION
          mvn versions:commit
          
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          
          # After creating release version, set the next development version
          mvn versions:set -DnewVersion=$NEXT_VERSION
          mvn versions:commit
          
          # Only commit if there are changes to the pom.xml
          if git diff --quiet pom.xml; then
            echo "No changes to pom.xml, skipping commit"
          else
            git add pom.xml
            git commit -m "[skip ci] Prepare for next development iteration $NEXT_VERSION"
            git push origin HEAD:${{ github.ref }}
          fi

      - name: Increment Node Version
        if: ${{ inputs.GLOBAL_FRAMEWORK == 'node' }}
        id: increment-version-node
        run: |
          # Get current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Split version into major, minor, and patch
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          
          # Increment version based on release type
          case "${{ github.event.inputs.release_type }}" in
            major)
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor + 1))
              patch=0
              ;;
            patch)
              patch=$((patch + 1))
              ;;
            *)
              echo "Invalid release type: ${{ github.event.inputs.release_type }}"
              exit 1
              ;;
          esac
          
          # Construct new version
          NEW_VERSION="${major}.${minor}.${patch}"
          
          # Update package.json
          npm version $NEW_VERSION --no-git-tag-version
          
          echo "RELEASE_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          git add package.json package-lock.json
          git commit -m "[skip ci] Bump version $NEW_VERSION"
          git push origin HEAD:${{ github.ref }}

      - name: Increment Git Version
        if: ${{ inputs.GLOBAL_FRAMEWORK == 'git' || inputs.GLOBAL_FRAMEWORK == 'did-science' }}
        id: increment-version-git
        run: |
          # Get the last version tag
          LAST_VERSION=$(git tag -l | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
          
          if [[ -z "$LAST_VERSION" ]]; then
            echo "No version tags found. Starting with 0.1.0"
            LAST_VERSION="0.1.0"
          fi
          
          # Split version into major, minor and patch
          IFS='.' read -r major minor patch <<< "$LAST_VERSION"
          
          # Increment version based on release type
          case "${{ github.event.inputs.release_type }}" in
            major)
              major=$((major + 1))
              RELEASE_VERSION="${major}.0.0"
              ;;
            minor)
              RELEASE_VERSION="${major}.$((minor + 1)).0"
              ;;
            patch)
              RELEASE_VERSION="${major}.${minor}.$((patch + 1))"
              ;;
            *)
              echo "Invalid release type: ${{ github.event.inputs.release_type }}"
              exit 1
              ;;
          esac
          
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Set SHORT_SHA env variable
        id: short_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build image maven
        if: ${{ inputs.GLOBAL_FRAMEWORK == 'maven' || inputs.GLOBAL_FRAMEWORK == 'triggered' || inputs.GLOBAL_FRAMEWORK == 'did-science' }}
        run: |
          docker build . -f "${{ inputs.PATH_TO_DOCKERFILE }}" -t "${{ inputs.GLOBAL_REPO_NAME }}/${{ inputs.GLOBAL_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}-${{ steps.short_sha.outputs.SHORT_SHA }}" \
          --build-arg DANUBETECH_MAVEN_INTERNAL_USERNAME=${{ env.MAVEN_USERNAME }} \
          --build-arg DANUBETECH_MAVEN_INTERNAL_PASSWORD=${{ env.MAVEN_PASSWORD }}

      - name: Build image generic
        if: ${{ inputs.GLOBAL_FRAMEWORK != 'maven' && inputs.GLOBAL_FRAMEWORK != 'triggered' }}
        run: |
          docker build . -f "${{ inputs.PATH_TO_DOCKERFILE }}" -t "${{ inputs.GLOBAL_REPO_NAME }}/${{ inputs.GLOBAL_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}-${{ steps.short_sha.outputs.SHORT_SHA }}"

      - name: Login user to repo and push image
        run: |
          echo "${{ env.DOCKER_PASSWORD }}" | docker login "${{ inputs.GLOBAL_REPO_NAME }}" -u "${{ env.DOCKER_USERNAME }}" --password-stdin
          docker push "${{ inputs.GLOBAL_REPO_NAME }}/${{ inputs.GLOBAL_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}-${{ steps.short_sha.outputs.SHORT_SHA }}"

      - name: Create and Push Git Tag
        if: success() && (steps.increment-version-maven.outcome == 'success' || steps.increment-version-node.outcome == 'success' || steps.increment-version-git.outcome == 'success')
        run: |
          git tag -a "${{ env.RELEASE_VERSION }}" -m "Release version ${{ env.RELEASE_VERSION }}"
          git push origin "${{ env.RELEASE_VERSION }}"

      - name: Cleanup Version Increment and Tag (if build fails)
        if: failure() && (steps.increment-version-maven.outcome == 'success' || steps.increment-version-node.outcome == 'success' || steps.increment-version-git.outcome == 'success')
        run: |
          git reset --hard HEAD~1 || true
          if git tag | grep -q "${{ env.RELEASE_VERSION }}"; then
            git tag -d "${{ env.RELEASE_VERSION }}" || true
            git push --delete origin "${{ env.RELEASE_VERSION }}" || true
          fi

      - name: Slack notification
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}