name: Maven release internal artifact

on:
  workflow_call:
    inputs:
      GLOBAL_MAVEN_REPO_SERVER_ID:
        required: true
        type: string
      PRIVATE_KEY_IDENTIFIER:
        required: true
        type: string
    secrets:
      VAULT_ADDR:
        required: true
      CI_SECRET_READER_PERIODIC_TOKEN:
        required: true
      VAULTCA:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:

  maven-release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
          caCertificate: ${{ secrets.VAULTCA }}
          secrets: |
            ci/data/gh-workflows/maven-danubetech-nexus username | MAVEN_USERNAME ;
            ci/data/gh-workflows/maven-danubetech-nexus password | MAVEN_PASSWORD ;
            ci/data/gh-workflows/maven-release-workflows ${{ inputs.PRIVATE_KEY_IDENTIFIER }} | SSH_PRIVATE_KEY

      - name: Release to Danubetech Nexus
        uses: qcastel/github-actions-maven-release@v1.12.31
        with:
          release-branch-name: main
          maven-repo-server-id: ${{ inputs.GLOBAL_MAVEN_REPO_SERVER_ID }}
          maven-repo-server-username: ${{ env.MAVEN_USERNAME }}
          maven-repo-server-password: ${{ env.MAVEN_PASSWORD }}
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
          version-minor: true
          maven-development-version-number: ${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}-SNAPSHOT
          maven-release-version-number: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.0
          git-release-bot-name: "admin-bot"
          git-release-bot-email: "admin@danubetech.com"
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs"

      - name: Slack notification
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}