name: Trivy check

on:
  workflow_call:
    inputs:
      GLOBAL_REPO_NAME:
        required: true
        type: string
      GLOBAL_IMAGE_NAME:
        required: true
        type: string

jobs:

  trivy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ inputs.GLOBAL_REPO_NAME }}/${{ inputs.GLOBAL_IMAGE_NAME }}"
          format: 'table'
          output: 'trivy-results.log'

      - name: Push Trivy scan results to Repo
        run: |
          if [[ $(git status --porcelain | grep "trivy-results.log") ]]; then
            echo "No changes to commit. Skipping..."
          else
            git config --global user.name "Trivy Scan"
            git config --global user.email "admin@danubetech.com"
            git add trivy-results.log
            git commit -m "ci: update trivy-results.log file"
            git push
          fi