name: Trivy scan

on:
  workflow_call:
    inputs:
      GLOBAL_REPO_NAME:
        required: true
        type: string
      GLOBAL_IMAGE_NAME:
        required: true
        type: string
    secrets:
      VAULT_ADDR:
        required: true
      CI_SECRET_READER_PERIODIC_TOKEN:
        required: true
      VAULTCA:
        required: true

jobs:

  trivy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
          caCertificate: ${{ secrets.VAULTCA }}
          secrets: |
            ci/data/gh-workflows/${{ inputs.GLOBAL_REPO_NAME }} username | DOCKER_USERNAME ;
            ci/data/gh-workflows/${{ inputs.GLOBAL_REPO_NAME }} password | DOCKER_PASSWORD 

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ inputs.GLOBAL_REPO_NAME }}/${{ inputs.GLOBAL_IMAGE_NAME }}"
          format: 'table'
          output: 'trivy-results.log'
        env:
          TRIVY_USERNAME: ${{ env.DOCKER_USERNAME }}
          TRIVY_PASSWORD: ${{ env.DOCKER_PASSWORD }}

      - name: Push Trivy scan results to Repo
        run: |
          git config --global user.name "Trivy Scan"
          git config --global user.email "admin@danubetech.com"
          git status
          ls -al
          if ! test -f "trivy-results.log"; then
            git add trivy-results.log
            git commit -m "ci: update trivy-results.log file"
            git push
          elif git diff --quiet HEAD -- "trivy-results.log"; then
            echo "No changes to commit. Skipping..."
          else
            git add trivy-results.log
            git commit -m "ci: update trivy-results.log file"
            git push
          fi